### PR TITLE
adding jenkins pipeline

### PR DESCRIPTION
**Pull request by ghost**
This PR is needed for [RES-32](https://huspy.atlassian.net/browse/RES-32)
It includes work for:
- Separating Dockerfiles for React and Flask 
- Create docker compose file to easily run the application in docker
- Adding jenkins pipeline 

Related PR: https://github.com/huspy/huspy-services/pull/12

### CODE REVIEW

**Review by javierdearcos — APPROVED** [review]
Not an expert in the matter, but everything seems good to me and I love having the services separate and coordinate with Docker compose.

Just two things that may have no sense but intrigue me:

- We are using 0.0.0.0 as an IP in one service. Could this be in some situations a little dangerous?
- I think we are using slack to send some notifications. Can we use Datadog for this? maybe not now but in the future

**Comment by huspy-souzaxx** [comment]
We still don't have the ECR for this project and the way that the Jenkinsfile is right now it won't work in the new cluster with argocd.

**Comment by nikitasu** [comment]
@huspy-souzaxx would it be possible to move forward with this today/tomorrow? As we agreed no special CPU setup needed, just to make sure this thing works :)

**Review by dflima — APPROVED** [review]
👏🏻

**Review by huspy-souzaxx — APPROVED** [review]

**Pull request merged**
